/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ssaoeeflcpxqtmejlajm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzYW9lZWZsY3B4cXRtZWpsYWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAzOTUwMzksImV4cCI6MjEwNTk3MTAzOX0.kfwY7CI3uD5hmc47z9-BaBbVinOkJ2KXzC_hHmJ6Vng"
